const TABLE_COMMENTS_BY_TABLE = Object.freeze({
  accounts: "시스템 계정 정보",

  app_email_log: "수험생 이메일 인증 코드 발송 및 검증 이력",
  app_form: "원서접수 및 서류제출 문항 정의",
  app_meta: "수험생 접수 이관 메타데이터",
  app_schedule: "전형별 접수 및 수험표 조회 일정",
  app_subm: "수험생 접수 응답 데이터",
  app_unit: "모집시기별 전형/계열/모집단위/전공 정의",

  print_log: "수험표 출력 이력",
  system_set: "시스템 공통 설정 저장소",
  templates: "수험표 양식 템플릿",
});

const COLUMN_COMMENTS_BY_TABLE = Object.freeze({
  accounts: Object.freeze({
    login_id: "로그인에 사용하는 계정 ID",
    display_name: "화면에 표시할 계정 이름",
    role: "계정 권한 구분",
    password_value: "로그인 비밀번호 해시값",
    password_temporary: "초기 비밀번호 상태 여부",
    last_login_at: "마지막 로그인 일시",
    created_at: "계정 생성 일시",
    updated_at: "계정 정보 수정 일시",
  }),

  app_email_log: Object.freeze({
    id: "이메일 인증 로그 식별자",
    applicant_name: "인증 요청자 이름",
    email: "인증 요청 이메일 주소",
    code_value: "이메일 인증 코드",
    expires_at: "인증 코드 만료 일시",
    verified_at: "인증 완료 일시",
    delivery_status: "이메일 발송 상태",
    delivery_message_id: "SMTP 서버가 반환한 메일 식별자",
    sent_at: "이메일 발송 성공 일시",
    failed_at: "이메일 발송 실패 일시",
    delivery_error: "이메일 발송 실패 사유",
    created_at: "인증 코드 발송 일시",
  }),
  app_form: Object.freeze({
    id: "접수 문항 식별자",
    form_scope: "문항 사용 화면(application: 원서접수, documents: 서류제출)",
    field_key: "접수 문항 고유 키",
    question_text: "문항 제목 또는 질문 내용",
    question_description: "문항 설명 문구",
    input_type: "문항 입력 방식",
    system_field_key: "시스템 예약 필드 키",
    options_json: "선택형 문항 옵션 JSON 배열",
    required: "필수 입력 여부",
    sort_order: "문항 화면 정렬 순서",
    active: "문항 사용 여부",
    created_at: "문항 생성 일시",
    updated_at: "문항 수정 일시",
  }),
  app_meta: Object.freeze({
    id: "접수 식별자(app_subm.id와 동일)",
    promoted_examinee_no: "접수 시 발급한 수험번호",
    promotion_override_json: "이관 시 적용한 수동 보정 데이터 JSON",
    promoted_at: "이전 시스템 처리 일시 (보존용)",
  }),
  app_schedule: Object.freeze({
    id: "접수 일정 식별자",
    track_name: "모집시기명",
    admission_code: "전형코드",
    admission_name: "전형명",
    applicant_schedule_start_at: "접수 시작 일시",
    applicant_schedule_end_at: "접수 종료 일시",
    admit_card_lookup_schedule_start_at: "수험표 조회 시작 일시",
    admit_card_lookup_schedule_end_at: "수험표 조회 종료 일시",
    document_submission_schedule_start_at: "서류 제출 시작 일시",
    document_submission_schedule_end_at: "서류 제출 종료 일시",
    created_at: "일정 생성 일시",
    updated_at: "일정 수정 일시",
  }),
  app_subm: Object.freeze({
    id: "접수 식별자",
    applicant_name: "접수자 이름",
    email: "접수자 이메일 주소",
    password_hash: "접수 조회/수정용 비밀번호 해시값",
    status: "접수 상태",
    field_key: "응답이 연결된 문항 키",
    answer_data: "문항 응답 데이터(JSON 또는 문자열)",
    created_at: "접수 답변 생성 일시",
    updated_at: "접수 답변 수정 일시",
  }),
  app_unit: Object.freeze({
    id: "전형 관리 식별자",
    track_name: "모집시기명",
    admission_code: "전형코드",
    admission_name: "전형명",
    series_code: "계열코드",
    series_name: "계열명",
    unit_code: "모집단위코드",
    unit_name: "모집단위명",
    major_code: "전공코드",
    major_name: "전공명",
    sort_order: "전형 관리 화면 정렬 순서",
    created_at: "전형 관리 데이터 생성 일시",
    updated_at: "전형 관리 데이터 수정 일시",
  }),

  print_log: Object.freeze({
    id: "출력 이력 식별자",
    examinee_no: "출력 대상 수험번호",
    print_count: "누적 출력 횟수",
    printed_at: "마지막 출력 일시",
  }),
  system_set: Object.freeze({
    setting_key: "시스템 설정 키",
    setting_value: "시스템 설정 값(JSON 또는 문자열)",
    updated_at: "설정 값 수정 일시",
  }),
  templates: Object.freeze({
    id: "수험표 양식 식별자",
    name: "수험표 양식명",
    description: "수험표 양식 설명",
    version_label: "양식 버전 표기",
    status: "양식 사용 상태",
    content_html: "양식 HTML 본문",
    created_at: "양식 생성 일시",
    updated_at: "양식 수정 일시",
  }),
});

module.exports = {
  COLUMN_COMMENTS_BY_TABLE,
  TABLE_COMMENTS_BY_TABLE,
};
